
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.testing.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.11
 * 2014-01-28T15:23:56.238-08:00
 * Generated source version: 2.3.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "CalculationService",
                      portName = "CalculationPort",
                      targetNamespace = "http://ws.testing.com/",
                      wsdlLocation = "http://localhost/Calculate/services/CalculationPort?wsdl",
                      endpointInterface = "com.testing.ws.CalcSEI")
                      
public class CalcSEIImpl implements CalcSEI {

    private static final Logger LOG = Logger.getLogger(CalcSEIImpl.class.getName());

    /* (non-Javadoc)
     * @see com.testing.ws.CalcSEI#multiply(int  arg0 ,)int  arg1 )*
     */
    public java.lang.String multiply(int arg0,int arg1) { 
        LOG.info("Executing operation multiply");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return252009957";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.testing.ws.CalcSEI#add(int  arg0 ,)int  arg1 )*
     */
    public java.lang.String add(int arg0,int arg1) { 
        LOG.info("Executing operation add");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1062943692";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.testing.ws.CalcSEI#subtract(int  arg0 ,)int  arg1 )*
     */
    public java.lang.String subtract(int arg0,int arg1) { 
        LOG.info("Executing operation subtract");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-1459948855";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.testing.ws.CalcSEI#divide(int  arg0 ,)int  arg1 )*
     */
    public java.lang.String divide(int arg0,int arg1) { 
        LOG.info("Executing operation divide");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.lang.String _return = "_return-647885505";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
